/**
 * The design-token source of truth — the two-layer seam (ADR-DS-3, FR-2).
 *
 * Layer 1 (`primitives`): raw Figma hues, authored in hex (ADR-DS-7). Every hue
 *   is hand-pinned from an observed Figma node EXCEPT the primary 50–900 ramp,
 *   which is synthetically generated by HSL-lightness interpolation from the
 *   single observed sample `#7f56d9` (Primary/600 on the Subscribe button) —
 *   no wider ramp exists in the file to hand-pin.
 * Layer 2 (`semanticLight` / `semanticDark`): shadcn-role aliases (`--primary`,
 *   `--foreground`, …). Each alias resolves to a primitive NAME, never to an
 *   inline hex — the type `PrimitiveName` makes an unbacked alias a compile
 *   error, not a silent CSS gap.
 *
 * `scripts/generate-tokens.ts` mechanically emits `@generated tokens.css` from
 * these maps. This file is hand-authored; `tokens.css` is not (never hand-edit
 * the generated artifact — change the input here and re-run `generate:tokens`).
 */

// --- pure hex ⇄ HSL helpers for the synthetic primary ramp (ADR-DS-7) -------
// Erasable TS only (native `node --strip-types` runs the generator): no enums,
// no namespaces, no parameter properties.

function hexToRgb(hex: string): [number, number, number] {
  const n = Number.parseInt(hex.slice(1), 16);
  return [(n >> 16) & 0xff, (n >> 8) & 0xff, n & 0xff];
}

function rgbToHex(r: number, g: number, b: number): string {
  const to2 = (v: number) => Math.round(v).toString(16).padStart(2, "0");
  return `#${to2(r)}${to2(g)}${to2(b)}`;
}

function rgbToHsl(r: number, g: number, b: number): [number, number, number] {
  const rn = r / 255;
  const gn = g / 255;
  const bn = b / 255;
  const max = Math.max(rn, gn, bn);
  const min = Math.min(rn, gn, bn);
  const l = (max + min) / 2;
  const d = max - min;
  if (d === 0) return [0, 0, l];
  const s = d / (1 - Math.abs(2 * l - 1));
  let h: number;
  if (max === rn) h = ((gn - bn) / d) % 6;
  else if (max === gn) h = (bn - rn) / d + 2;
  else h = (rn - gn) / d + 4;
  h *= 60;
  if (h < 0) h += 360;
  return [h, s, l];
}

function hslToHex(h: number, s: number, l: number): string {
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = l - c / 2;
  const [r, g, b] =
    h < 60
      ? [c, x, 0]
      : h < 120
        ? [x, c, 0]
        : h < 180
          ? [0, c, x]
          : h < 240
            ? [0, x, c]
            : h < 300
              ? [x, 0, c]
              : [c, 0, x];
  return rgbToHex((r + m) * 255, (g + m) * 255, (b + m) * 255);
}

/** Primary/600 — the single observed Figma sample (D-4). */
const PRIMARY_600 = "#7f56d9";

interface PrimaryRamp {
  primary50: string;
  primary100: string;
  primary200: string;
  primary300: string;
  primary400: string;
  primary500: string;
  primary600: string;
  primary700: string;
  primary800: string;
  primary900: string;
}

/**
 * Build the primary 50–900 ramp: keep the sample's hue + saturation, walk a
 * fixed lightness scale, and pin 600 to the exact observed hex so the one real
 * value stays pixel-true (the other steps are approximations by ADR-DS-7).
 */
function primaryRamp(): PrimaryRamp {
  const [h, s] = rgbToHsl(...hexToRgb(PRIMARY_600));
  // Hand-tuned lightness stops approximating a conventional 50–900 ramp. Only
  // 600 is an observed Figma value (ADR-DS-7); the rest are approximations, so
  // exact stop spacing is not load-bearing. 600's lightness is a sentinel (`0`)
  // — it is special-cased to the exact `PRIMARY_600` hex below, never computed.
  const lightness: [keyof PrimaryRamp, number][] = [
    ["primary50", 0.97],
    ["primary100", 0.93],
    ["primary200", 0.85],
    ["primary300", 0.76],
    ["primary400", 0.66],
    ["primary500", 0.61],
    ["primary600", 0],
    ["primary700", 0.47],
    ["primary800", 0.38],
    ["primary900", 0.3],
  ];
  const ramp = {} as PrimaryRamp;
  for (const [name, l] of lightness) {
    ramp[name] = name === "primary600" ? PRIMARY_600 : hslToHex(h, s, l);
  }
  return ramp;
}

/**
 * Layer 1 — primitive palette. Hand-pinned Figma hues plus the generated
 * primary ramp. Dark-frame-only hues (bg `#090d1f`, body `#c0c5d0`) land with
 * Task 008; only the ramp, the `--primary-strong` escape hatch, and the shared
 * light/neutral hues are authored here.
 */
export const primitives = {
  ...primaryRamp(),
  /**
   * Dark-mode-only escape hatch (ADR-DS-4). `#7f56d9` is ≈3.89:1 on the dark
   * frame `#090d1f` (fails AA for small text); `#a082e3` is ≈6.2:1. Defined now
   * so a future dark-mode contrast fix is a semantic re-point, not a hunt.
   */
  primaryStrong: "#a082e3",
  white: "#ffffff",
  black: "#000000",
  headingLight: "#181a2a",
  bodyLight: "#667085",
  accentByline: "#6941c6",
} as const;

type PrimitiveName = keyof typeof primitives;

/**
 * Layer 2 (light) — semantic aliases → primitive names. `--primary` maps to the
 * observed Primary/600; see the `primaryStrong` primitive above for the
 * dark-mode contrast rationale (ADR-DS-4), which is why `--primary` stays the
 * pixel-true Figma hue here rather than being pre-corrected.
 */
export const semanticLight = {
  "--background": "white",
  "--foreground": "headingLight",
  "--muted-foreground": "bodyLight",
  "--primary": "primary600",
  "--primary-foreground": "white",
  "--accent": "accentByline",
} as const satisfies Record<string, PrimitiveName>;

/**
 * Layer 2 (dark) — intentionally empty until Task 008 (FR-9) maps the observed
 * Figma dark-frame values onto these same aliases. The generator already emits
 * a `.dark {}` block from this map, so 008 is a pure token-value edit here plus
 * a `generate:tokens` re-run — never a generator change or a `tokens.css`
 * hand-edit (ADR-DS-5).
 */
export const semanticDark = {} as const satisfies Record<string, PrimitiveName>;
