/**
 * The design-token source of truth - the two-layer seam (ADR-DS-3, FR-2).
 *
 * Layer 1 (`primitives`): raw Figma hues, authored in hex (ADR-DS-7). Every hue
 *   is hand-pinned from an observed Figma node EXCEPT the primary 50–900 ramp,
 *   which is synthetically generated by HSL-lightness interpolation from the
 *   single observed sample `#7f56d9` (Primary/600 on the Subscribe button) -
 *   no wider ramp exists in the file to hand-pin.
 * Layer 2 (`semanticLight` / `semanticDark`): shadcn-role aliases (`--primary`,
 *   `--foreground`, …). Each alias resolves to a primitive NAME, never to an
 *   inline hex - the type `PrimitiveName` makes an unbacked alias a compile
 *   error, not a silent CSS gap.
 *
 * `scripts/generate-tokens.ts` mechanically emits `@generated tokens.css` from
 * these maps. This file is hand-authored; `tokens.css` is not (never hand-edit
 * the generated artifact - change the input here and re-run `generate:tokens`).
 */

// --- pure hex ⇄ HSL helpers for the synthetic primary ramp (ADR-DS-7) -------
// Erasable TS only (native `node --strip-types` runs the generator): no enums,
// no namespaces, no parameter properties.

function hexToRgb(hex: string): [number, number, number] {
  const n = Number.parseInt(hex.slice(1), 16);
  return [(n >> 16) & 0xff, (n >> 8) & 0xff, n & 0xff];
}

function rgbToHex(r: number, g: number, b: number): string {
  const to2 = (v: number) => Math.round(v).toString(16).padStart(2, "0");
  return `#${to2(r)}${to2(g)}${to2(b)}`;
}

function rgbToHsl(r: number, g: number, b: number): [number, number, number] {
  const rn = r / 255;
  const gn = g / 255;
  const bn = b / 255;
  const max = Math.max(rn, gn, bn);
  const min = Math.min(rn, gn, bn);
  const l = (max + min) / 2;
  const d = max - min;
  if (d === 0) return [0, 0, l];
  const s = d / (1 - Math.abs(2 * l - 1));
  let h: number;
  if (max === rn) h = ((gn - bn) / d) % 6;
  else if (max === gn) h = (bn - rn) / d + 2;
  else h = (rn - gn) / d + 4;
  h *= 60;
  if (h < 0) h += 360;
  return [h, s, l];
}

function hslToHex(h: number, s: number, l: number): string {
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = l - c / 2;
  const [r, g, b] =
    h < 60
      ? [c, x, 0]
      : h < 120
        ? [x, c, 0]
        : h < 180
          ? [0, c, x]
          : h < 240
            ? [0, x, c]
            : h < 300
              ? [x, 0, c]
              : [c, 0, x];
  return rgbToHex((r + m) * 255, (g + m) * 255, (b + m) * 255);
}

/** Primary/600 - the single observed Figma sample (D-4). */
const PRIMARY_600 = "#7f56d9";

interface PrimaryRamp {
  primary50: string;
  primary100: string;
  primary200: string;
  primary300: string;
  primary400: string;
  primary500: string;
  primary600: string;
  primary700: string;
  primary800: string;
  primary900: string;
}

/**
 * Build the primary 50–900 ramp: keep the sample's hue + saturation, walk a
 * fixed lightness scale, and pin 600 to the exact observed hex so the one real
 * value stays pixel-true (the other steps are approximations by ADR-DS-7).
 */
function primaryRamp(): PrimaryRamp {
  const [h, s] = rgbToHsl(...hexToRgb(PRIMARY_600));
  // Hand-tuned lightness stops approximating a conventional 50–900 ramp. Only
  // 600 is an observed Figma value (ADR-DS-7); the rest are approximations, so
  // exact stop spacing is not load-bearing. 600's lightness is a sentinel (`0`)
  // - it is special-cased to the exact `PRIMARY_600` hex below, never computed.
  const lightness: [keyof PrimaryRamp, number][] = [
    ["primary50", 0.97],
    ["primary100", 0.93],
    ["primary200", 0.85],
    ["primary300", 0.76],
    ["primary400", 0.66],
    ["primary500", 0.61],
    ["primary600", 0],
    ["primary700", 0.47],
    ["primary800", 0.38],
    ["primary900", 0.3],
  ];
  const ramp = {} as PrimaryRamp;
  for (const [name, l] of lightness) {
    ramp[name] = name === "primary600" ? PRIMARY_600 : hslToHex(h, s, l);
  }
  return ramp;
}

/**
 * Layer 1 - primitive palette. Hand-pinned Figma hues plus the generated
 * primary ramp, including the Task 008 dark-frame hues (bg `#090d1f`, body
 * `#c0c5d0`).
 */
export const primitives = {
  ...primaryRamp(),
  /**
   * Dark-mode-only escape hatch (ADR-DS-4). `#7f56d9` is ≈3.89:1 on the dark
   * frame `#090d1f` (fails AA for small text); `#a082e3` is ≈6.2:1. Defined now
   * so a future dark-mode contrast fix is a semantic re-point, not a hunt.
   */
  primaryStrong: "#a082e3",
  white: "#ffffff",
  black: "#000000",
  headingLight: "#181a2a",
  bodyLight: "#667085",
  accentByline: "#6941c6",
  /**
   * Figma dark frame (node `614:679`, ADR-DS-5) - hand-pinned literals, never
   * run through `hslToHex`/`primaryRamp` (ADR-DS-7: only the primary 50–900
   * ramp is synthetic). `accentBylineDark` intentionally equals `accentByline`
   * - the byline accent is unchanged between light and dark frames.
   */
  backgroundDark: "#090d1f",
  headingDark: "#ffffff",
  bodyDark: "#c0c5d0",
  accentBylineDark: "#6941c6",
  /**
   * Dark surface + border hues (ADR-DS-5) - the elevated card/popover surface
   * and divider on the dark frame `#090d1f`. Landing these lets `--card`,
   * `--popover`, and `--border` re-point in `semanticDark` so `bg-card`/
   * `border-border` stop falling through to their light `:root` values (a white
   * card on the dark page). Untitled-UI-style dark neutrals; `cardDark` is a
   * subtle elevation above `backgroundDark`.
   */
  cardDark: "#111633",
  borderDark: "#242b47",
  /**
   * Dark `--muted` (inline-code chip bg on the blog Post body). Without this,
   * `--muted` fell through to the light `gray50` (near-white) on the dark
   * page - washed-out, low-contrast. A step above `cardDark` keeps inline
   * code visibly distinct from the surrounding surface.
   */
  mutedDark: "#1c2247",
  /**
   * shadcn-role primitives (Task 004, FR-4) - restyling the stock shadcn
   * primitive set (badge/button/input/card/avatar/navigation-menu/sheet) to
   * the Figma light look through the semantic layer. Untitled-UI-style
   * neutrals/red, the same family the primary ramp is drawn from.
   */
  gray50: "#f9fafb",
  gray100: "#f2f4f7",
  gray200: "#eaecf0",
  gray300: "#d0d5dd",
  gray700: "#344054",
  red50: "#fef3f2",
  red600: "#d92d20",
  /**
   * The 8 Badge category hues (FR-6) - each a soft-tint background + a
   * darker-shade foreground, the Untitled-UI badge convention. None tied to
   * a category *name* beyond the hue itself (D-6-analogue for badges).
   */
  categoryVioletBg: "#f4f3ff",
  categoryVioletFg: "#5925dc",
  categoryIndigoBg: "#eef4ff",
  categoryIndigoFg: "#3538cd",
  categoryPinkBg: "#fdf2fa",
  categoryPinkFg: "#c11574",
  categorySkyBg: "#f0f9ff",
  categorySkyFg: "#026aa2",
  categoryGreenBg: "#ecfdf3",
  categoryGreenFg: "#027a48",
  categoryGrayBlueBg: "#f8f9fc",
  categoryGrayBlueFg: "#363f72",
  categoryOrangeBg: "#fff6ed",
  categoryOrangeFg: "#c4320a",
  categoryRoseBg: "#fef3f2",
  categoryRoseFg: "#b42318",
  /**
   * Shiki syntax-highlighting palette (FR-8, ADR-RM-3), re-homed from
   * `theme/theme.ts` `brand`. Deliberately ungrouped and NOT routed through
   * `semanticLight`/`semanticDark` - code blocks stay a single dark island in
   * both themes (OQ-2), so there is no light variant to alias.
   */
  shikiBg: "#141b22",
  shikiFg: "#e2e8f0",
  shikiTokenComment: "#64748b",
  shikiTokenKeyword: "#38bdf8",
  shikiTokenString: "#84cc16",
  shikiTokenConstant: "#f97316",
  shikiTokenFunction: "#a855f7",
  shikiTokenVariable: "#7dd3fc",
} as const;

type PrimitiveName = keyof typeof primitives;

/**
 * Layer 2 (light) - semantic aliases → primitive names. `--primary` maps to the
 * observed Primary/600; see the `primaryStrong` primitive above for the
 * dark-mode contrast rationale (ADR-DS-4), which is why `--primary` stays the
 * pixel-true Figma hue here rather than being pre-corrected.
 */
export const semanticLight = {
  "--background": "white",
  "--foreground": "headingLight",
  "--muted": "gray50",
  "--muted-foreground": "bodyLight",
  "--primary": "primary600",
  "--primary-foreground": "white",
  "--secondary": "gray100",
  "--secondary-foreground": "gray700",
  "--destructive": "red600",
  "--destructive-foreground": "white",
  "--accent": "accentByline",
  "--accent-foreground": "white",
  "--card": "white",
  "--card-foreground": "headingLight",
  "--popover": "white",
  "--popover-foreground": "headingLight",
  "--border": "gray200",
  "--input": "gray300",
  "--ring": "primary600",
  "--badge-violet-bg": "categoryVioletBg",
  "--badge-violet-fg": "categoryVioletFg",
  "--badge-indigo-bg": "categoryIndigoBg",
  "--badge-indigo-fg": "categoryIndigoFg",
  "--badge-pink-bg": "categoryPinkBg",
  "--badge-pink-fg": "categoryPinkFg",
  "--badge-sky-bg": "categorySkyBg",
  "--badge-sky-fg": "categorySkyFg",
  "--badge-green-bg": "categoryGreenBg",
  "--badge-green-fg": "categoryGreenFg",
  "--badge-gray-blue-bg": "categoryGrayBlueBg",
  "--badge-gray-blue-fg": "categoryGrayBlueFg",
  "--badge-orange-bg": "categoryOrangeBg",
  "--badge-orange-fg": "categoryOrangeFg",
  "--badge-rose-bg": "categoryRoseBg",
  "--badge-rose-fg": "categoryRoseFg",
} as const satisfies Record<string, PrimitiveName>;

/**
 * Layer 2 (dark) - Task 008 (FR-9): the Figma dark frame (node `614:679`)
 * mapped onto the SAME alias names `semanticLight` uses (a strict subset, no
 * dark-only aliases). Aliases not yet re-pointed here fall through to the
 * `:root` light value (ADR-DS-5); a pure token-value edit plus a
 * `generate:tokens` re-run - never a generator change or a `tokens.css`
 * hand-edit.
 */
export const semanticDark = {
  "--background": "backgroundDark",
  "--foreground": "headingDark",
  "--primary": "primaryStrong",
  "--muted": "mutedDark",
  "--muted-foreground": "bodyDark",
  "--accent": "accentBylineDark",
  "--card": "cardDark",
  "--card-foreground": "headingDark",
  "--popover": "cardDark",
  "--popover-foreground": "headingDark",
  "--border": "borderDark",
} as const satisfies Record<string, PrimitiveName>;

/**
 * Dimension token layer - same two-layer pattern as the color tokens, for the
 * magic px values previously inlined as Tailwind arbitrary values in `ds/`
 * (`max-w-[1216px]`, `py-[30px]`, `rounded-[29px]`, …). Theme-invariant: no
 * light/dark split, `:root` only.
 */
export const dimensionPrimitives = {
  contentMeasure: "1216px",
  drawerMeasure: "320px",
  pillRadius: "29px",
  spaceHeaderY: "30px",
  spaceNavbarY: "10px",
  spaceNavGap: "14px",
  spaceNavActive: "5px",
  spaceMastheadTop: "50px",
  /**
   * Task 005 (typography-measure-constrained): the Post body prose column's
   * measure, in `ch` (character-count-relative), not `px` - a reading-measure
   * constraint scales with the resolved font rather than pinning an arbitrary
   * pixel width. Applied directly to `ArticleProse`'s `<article>` so the
   * rendered element's own `max-width` is the literal 64ch contract the e2e
   * suite measures against, replacing the previous ad-hoc `max-w-3xl` (64rem)
   * wrapper approximation.
   */
  proseMeasure: "64ch",
  /** Meter atom (FR-6, D-8): track thickness and the gap between track and its legend. */
  meterTrackHeight: "8px",
  spaceMeterLegendGap: "6px",
} as const;

type DimensionPrimitiveName = keyof typeof dimensionPrimitives;

/**
 * Semantic dimension aliases, each carrying the Tailwind v4 `@theme`
 * namespace prefix its consumers need (`--container-*` → `max-w-<name>`,
 * `--spacing-*` → `py-/gap-/pb-/mt-<name>`, `--radius-*` → `rounded-<name>`),
 * so the generator bridges them into `@theme inline` verbatim, unlike the
 * `--color-*` re-prefixing the color aliases get.
 */
export const semanticDimensions = {
  "--container-content": "contentMeasure",
  "--container-drawer": "drawerMeasure",
  "--radius-pill": "pillRadius",
  "--spacing-header-y": "spaceHeaderY",
  "--spacing-navbar-y": "spaceNavbarY",
  "--spacing-nav-gap": "spaceNavGap",
  "--spacing-nav-active": "spaceNavActive",
  "--spacing-masthead-top": "spaceMastheadTop",
  "--container-prose-measure": "proseMeasure",
  "--spacing-meter-track": "meterTrackHeight",
  "--spacing-meter-legend-gap": "spaceMeterLegendGap",
} as const satisfies Record<string, DimensionPrimitiveName>;
