/**
 * `generate:tokens` — emits `@generated src/theme/tokens.css` from the two-layer
 * token maps in `src/theme/tokens.ts` (FR-2, ADR-DS-3).
 *
 * Runs under Node's native TypeScript strip (`node scripts/generate-tokens.ts`)
 * — no `tsx`/`ts-node` dependency (sec-deps-pinned-and-locked). The emitter and
 * path guard are exported pure functions so `src/theme/tokens.test.ts` can call
 * them in-process; only `main()` (behind `import.meta.main`) touches the disk.
 */
import { writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  dimensionPrimitives,
  primitives,
  semanticDark,
  semanticDimensions,
  semanticLight,
} from "../src/theme/tokens.ts";

// Hardcoded literal output path (sec-codegen-path-safety) — never derived from
// env, CLI args, or any external input.
const OUTPUT_PATH = "src/theme/tokens.css";

const BANNER = [
  "/*",
  " * @generated by `npm run generate:tokens` — DO NOT EDIT BY HAND.",
  " * Source of truth: src/theme/tokens.ts. Change a token there and re-run the",
  " * generator; hand-edits are overwritten (generated-css-not-hand-edited).",
  " */",
].join("\n");

/** camelCase / digit-suffixed key → kebab CSS-var suffix (`primary600` → `primary-600`). */
export function kebab(key: string): string {
  return key
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/([a-zA-Z])([0-9])/g, "$1-$2")
    .toLowerCase();
}

function declarations(entries: [string, string][], indent: string): string {
  return entries.map(([prop, value]) => `${indent}${prop}: ${value};`).join("\n");
}

/**
 * Emit the full stylesheet. Deterministic: object key order is the sole
 * ordering, no timestamps or environment input, so repeated runs are
 * byte-identical (tokens-codegen-deterministic).
 */
export function emitTokensCss(): string {
  const primitiveDecls = Object.entries(primitives).map(
    ([name, hex]) => [`--${kebab(name)}`, hex] as [string, string]
  );
  const semanticDecls = (map: Record<string, string>): [string, string][] =>
    Object.entries(map).map(([alias, primitive]) => [alias, `var(--${kebab(primitive)})`]);

  const dimensionPrimitiveDecls = Object.entries(dimensionPrimitives).map(
    ([name, value]) => [`--${kebab(name)}`, value] as [string, string]
  );
  const dimensionAliasDecls = Object.entries(semanticDimensions).map(
    ([alias, primitive]) => [alias, `var(--${kebab(primitive)})`] as [string, string]
  );

  const root = [
    ":root {",
    "  /* primitives */",
    declarations(primitiveDecls, "  "),
    "",
    "  /* semantic aliases → primitives */",
    declarations(semanticDecls(semanticLight), "  "),
    "",
    "  /* dimension primitives */",
    declarations(dimensionPrimitiveDecls, "  "),
    "",
    "  /* semantic dimension aliases → dimension primitives */",
    declarations(dimensionAliasDecls, "  "),
    "}",
  ].join("\n");

  // Dark-aware from the start (ADR-DS-5): the `.dark` block is emitted even
  // while `semanticDark` is empty, so Task 008 only fills values + re-runs.
  const dark = [".dark {", declarations(semanticDecls(semanticDark), "  "), "}"]
    .filter((line) => line !== "")
    .join("\n");

  // ADR-DS-3: bridge each semantic alias into Tailwind v4's token space so
  // `bg-background`/`text-foreground`/etc. resolve to the seam. `inline` keeps
  // values as `var(--…)` references. Emitted here (not hand-authored in
  // globals.css) so the bridge auto-tracks the alias set and biome never has to
  // parse the Tailwind-specific `@theme` directive in a hand-edited file.
  const colorBridgeDecls = Object.keys(semanticLight).map(
    (alias) => [`--color-${alias.replace(/^--/, "")}`, `var(${alias})`] as [string, string]
  );
  // Dimension aliases reuse the Tailwind `@theme` namespace (`--container-*`,
  // `--spacing-*`, `--radius-*`) *as* their own name, so bridging an alias to
  // `var(${alias})` is a circular `--x: var(--x)` self-reference — invalid at
  // computed-value time, collapsing e.g. `rounded-pill` to `0`. Bridge each
  // alias to its primitive instead (mirrors `dimensionAliasDecls` and the
  // `--color-*` bridge, whose re-prefixing sidesteps the collision).
  const dimensionBridgeDecls = Object.entries(semanticDimensions).map(
    ([alias, primitive]) => [alias, `var(--${kebab(primitive)})`] as [string, string]
  );
  const theme = [
    "@theme inline {",
    declarations([...colorBridgeDecls, ...dimensionBridgeDecls], "  "),
    "}",
  ].join("\n");

  return `${BANNER}\n\n${root}\n\n${dark}\n\n${theme}\n`;
}

/**
 * Fail fast if `candidate` resolves outside `<repoRoot>/src/theme`
 * (sec-codegen-path-safety). Guards the write even though the only real caller
 * passes a hardcoded literal.
 */
export function assertInsideThemeDir(repoRoot: string, candidate: string): void {
  const themeDir = resolve(repoRoot, "src/theme");
  const target = resolve(candidate);
  const rel = relative(themeDir, target);
  if (rel.startsWith("..") || resolve(themeDir, rel) !== target) {
    throw new Error(`Refusing to write outside src/theme: ${target}`);
  }
}

export function writeTokensCss(repoRoot: string): string {
  const target = resolve(repoRoot, OUTPUT_PATH);
  assertInsideThemeDir(repoRoot, target);
  writeFileSync(target, emitTokensCss());
  return target;
}

function main(): void {
  const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  const target = writeTokensCss(repoRoot);
  console.log(`Generated ${relative(repoRoot, target)}`);
}

// `import.meta.main` is true only when this file is the entrypoint (Node ≥24),
// so importing the pure helpers in tests never triggers a disk write.
if ((import.meta as ImportMeta & { main?: boolean }).main) main();
